### ISSUE TITLE
latest umd version is a valid bundle

### ISSUE THREAD

**Issue by kagawagao** [alibaba/BizGoblin#10]
version of `goblin` bundled into the latest version(`v0.1.9`) of `bizgoblin` is still in version `0.1.7`,  so [`checkChartConfig`](https://github.com/alibaba/BizGoblin/blob/1cea770791097e26bdb6bb5abce4631daac06d96/packages/goblin/src/core/CommonChart.ts#L148-L153) is still error

**Comment by RaulZuo** [comment]
see v0.2.0
