### ISSUE TITLE
F2中的 PieLabel 在 BizGoblin 中如何使用呢？

### ISSUE THREAD

**Issue by Running00** [alibaba/BizGoblin#6]

**Comment by RaulZuo** [comment]
升级到0.2.x版本，通过按需加载
js应用: `import PieLabel from 'bizgoblin/lib/plugin/PieLabel'`
ts应用 `import PieLabel from 'bizgoblin/es/plugin/PieLabel'`

**Comment by MuYunyun** [comment]
hi, where is the api about PieLabel?
